services:
  redis-node1:
    image: redis:7
    container_name: redis-node1
    ports:
      - "6379:6379"

  redis-node2:
    image: redis:7
    container_name: redis-node2
    command: redis-server --replicaof redis-node1 6379
    depends_on:
      - redis-node1
    ports:
      - "6380:6379"

  etcd:
    image: registry.k8s.io/etcd:3.5.21-0
    container_name: etcd
    command:
      - /usr/local/bin/etcd
      - --name=node1
      - --data-dir=/etcd-data
      - --advertise-client-urls=http://0.0.0.0:2379
      - --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"